Experienced an error traced back to cipher.py

Changed code in the "cipher.py" script to account for some stuff that YouTube did to break the functionality

lib > python3.10 > site-packages > pytube > cipher.py > get_throttling_Function_name

Solution found at https://github.com/pytube/pytube/issues/1954#issuecomment-2218287594

    function_patterns = [
        # https://github.com/ytdl-org/youtube-dl/issues/29326#issuecomment-865985377
        # https://github.com/yt-dlp/yt-dlp/commit/48416bc4a8f1d5ff07d5977659cb8ece7640dcd8
        # var Bpa = [iha];
        # ...
        # a.C && (b = a.get("n")) && (b = Bpa[0](b), a.set("n", b),
        # Bpa.length || iha("")) }};
        # In the above case, `iha` is the relevant function name
        r'a\.[a-zA-Z]\s*&&\s*\([a-z]\s*=\s*a\.get\("n"\)\)\s*&&.*?\|\|\s*([a-z]+)',
        r'\([a-z]\s*=\s*([a-zA-Z0-9$]+)(\[\d+\])?\([a-z]\)',
        r'\([a-z]\s*=\s*([a-zA-Z0-9$]+)(\[\d+\])\([a-z]\)',
    ]

Pytube repo hasn't been updated in a while as of August 2024. May want to find a replacement, but it's working for now.